Ben and Alex Scribe Notes Lecture 12
kshitijgoel007/16831-Spring-2022 pull request #25
Opened 2022-03-04 02:21 UTC by apletta

Lecture 12 scribe notes. Submitted by Alex Pletta and Benjamin Younes.

2022-03-20 19:45 UTC, lagrassa commented
### Review
1. Reviews MABs
1.  Doesn't include Adaboost or PAC learning from last lecture but the connection to this lecture isn't particularly apparent so that's reasonable
1. Including the MAB assumptions was good since it's particularly relevant for this lecture

### Summary
1. Overall nice connecting the pieces of the lecture together, such as motivating why certain bounds were derived
1. Good explicitly defining notation
1. Derives $\epsilon$ from Hoeffing's inequality
1. Since we have not used an inequality as a potential function before in this class
, it would be helpful to briefly outline how an inequality as a potential function works and how it is used differently.
1. Confusing formatting error in 2.3.1 please fix! (After equation 43)
1. Includes some intuition for the union bound
### 
Grading notes
1. High-quality scribe notes, definitely in upper percentile for thoroughness, submitted within 3 days.

2022-03-20 19:48 UTC, lagrassa requested changes
1 very minor formatting fix to please do by Friday 3/25. Otherwise good work!

2022-03-27 15:12 UTC, merged

2022-03-27 15:12 UTC, lagrassa commented
Ignoring formatting error, not worth it.

2022-03-27 21:00 UTC, apletta commented
@lagrassa Sorry we're just getting around to this PR after finishing the homework last night, thank you for merging!